---
- name: Configuring F5 GSLB
  hosts: localhost
  connection: local
  vars_files:
    - /tmp/gslb_info.json
  gather_facts: false
  vars:
    provider:
      password: "{{f5_pass}}"
      server: "{{mgmt_ip}}"
      user: "{{f5_user}}"
      validate_certs: no
      server_port: 443
  tasks:
 
  - name: Create America Record
    bigip_gtm_topology_record:
      source:
        region: america
      destination:
        pool: america_pool
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create Europe Record
    bigip_gtm_topology_record:
      source:
        region: europe
      destination:
        pool: europe_pool
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create Asia Record
    bigip_gtm_topology_record:
      source:
        region: asia
      destination:
        pool: asia_pool
      provider: "{{ provider }}"
    delegate_to: localhost