---
- name: Configuring F5 GSLB
  hosts: localhost
  connection: local
  vars_files:
    - /tmp/gslb_info.json
  gather_facts: false
  vars:
    provider:
      password: "{{f5_pass}}"
      server: "{{mgmt_ip}}"
      user: "{{f5_user}}"
      validate_certs: no
      server_port: 443
  tasks:
  - name: Wait for BIGIP LTM to be on a ready state
    bigip_wait:
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Wait for BIGIP GTM to be on a ready state
    uri:
      url: https://{{mgmt_ip}}/mgmt/tm/gtm/listener/
      user: "{{f5_user}}"
      password: "{{f5_pass}}"
      method: GET
      force_basic_auth: yes
      validate_certs: no
    register: gtm_listener_check
    changed_when: gtm_listener_check.status == 200  
    retries: 120
    until: gtm_listener_check.status == 200
    delay: 3

  - name: Create a DNS Listener
    uri:
      url: https://{{mgmt_ip}}/mgmt/tm/gtm/listener/
      user: "{{f5_user}}"
      password: "{{f5_pass}}"
      method: POST
      body: "{\"name\": \"listener\",\"address\": \"{{dns_private_ip}}\",\"port\": 53}"
      force_basic_auth: yes
      body_format: json
      validate_certs: no
      status_code: [200,202,409]
    register: gtm_listener_add_POST_return

  - name: Create GSLB DC
    bigip_gtm_datacenter:
      name: "azure"
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create GTM_Server
    bigip_gtm_server:
      name: GTM_Server
      datacenter: /Common/azure
      server_type: bigip
      link_discovery: disabled
      virtual_server_discovery: disabled
      devices:
        - name: gtm_server
          address: 10.1.10.4
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create Europe Region
    bigip_gtm_topology_region:
      name: europe
      region_members:
        - continent: AF
        - continent: EU
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create America Region
    bigip_gtm_topology_region:
      name: america
      region_members:
        - continent: NA
        - continent: SA
        - continent: --
        - continent: AN
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create Asia Region
    bigip_gtm_topology_region:
      name: asia
      region_members:
        - continent: OC
        - continent: AS
      provider: "{{ provider }}"
    delegate_to: localhost

   - name: Create a BigIP GTM pool
     bigip_gtm_pool:
      name: bigip_pool
      preferred_lb_method: round-robin
      alternate_lb_method: round-robin
      ttl: 10
      type: a
      max_answers_returned: 50
      provider: "{{ provider }}"
    delegate_to: localhost


   - name: Create a Europe GTM pool
     bigip_gtm_pool:
      name: europe_pool
      preferred_lb_method: topology
      alternate_lb_method: round-robin
      ttl: 10
      type: a
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create a America GTM pool
    bigip_gtm_pool:
      name: america_pool
      preferred_lb_method: topology
      alternate_lb_method: round-robin
      ttl: 10
      type: a
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create a Asia GTM pool
    bigip_gtm_pool:
      name: asia_pool
      preferred_lb_method: topology
      alternate_lb_method: round-robin
      ttl: 10
      type: a
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create a Europe GTM App pool
    bigip_gtm_pool:
      name: app_europe_pool
      preferred_lb_method: round-robin
      alternate_lb_method: round-robin
      ttl: 10
      type: a
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create a America GTM App pool
    bigip_gtm_pool:
      name: app_america_pool
      preferred_lb_method: round-robin
      alternate_lb_method: round-robin
      ttl: 10
      type: a
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create a Asia GTM App pool
    bigip_gtm_pool:
      name: app_asia_pool
      preferred_lb_method: round-robin
      alternate_lb_method: round-robin
      ttl: 10
      type: a
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create America Record
    bigip_gtm_topology_record:
      source:
        region: america
      destination:
        pool: america_pool
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create Europe Record
    bigip_gtm_topology_record:
      source:
        region: europe
      destination:
        pool: europe_pool
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create Asia Record
    bigip_gtm_topology_record:
      source:
        region: asia
      destination:
        pool: asia_pool
      provider: "{{ provider }}"
    delegate_to: localhost


  - name: Create www.f5demo.cloud wideIP
    bigip_gtm_wide_ip:
      pool_lb_method: topology
      last_resort_pool: america_pool
      name: www.f5demo.cloud
      type: a
      pools:
        - name: america_pool
        - name: europe_pool
        - name: asia_pool
      provider: "{{ provider }}"
    delegate_to: localhost


  - name: Create eu.f5demo.cloud wideIP
    bigip_gtm_wide_ip:
      pool_lb_method: topology
      last_resort_pool: app_europe_pool
      name: eu.f5demo.cloud
      type: a
      pools:
        - name: app_europe_pool
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create us.f5demo.cloud wideIP
    bigip_gtm_wide_ip:
      pool_lb_method: topology
      last_resort_pool: app_america_pool
      name: us.f5demo.cloud
      type: a
      pools:
        - name: app_america_pool
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create as.f5demo.cloud wideIP
    bigip_gtm_wide_ip:
      pool_lb_method: topology
      last_resort_pool: app_asia_pool
      name: as.f5demo.cloud
      type: a
      pools:
        - name: app_asia_pool
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Create bigip.f5demo.cloud wideIP
    bigip_gtm_wide_ip:
      pool_lb_method: round-robin
      last_resort_pool: bigip_pool
      name: bigip.f5demo.cloud
      type: a
      pools:
        - name: bigip_pool
      provider: "{{ provider }}"
    delegate_to: localhost