{
 "title": "F5 Real Time Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "F5 Devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"f5\"})"
    }
   ]
  },
  {
   "title": "2xx Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(f5_2xxResp{}[$__range]))"
    }
   ]
  },
  {
   "title": "3xx Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(f5_3xxResp{}[$__range]))"
    }
   ]
  },
  {
   "title": "4xx Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(f5_4xxResp{}[$__range]))"
    }
   ]
  },
  {
   "title": "5xx Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(f5_5xxResp{}[$__range]))"
    }
   ]
  },
  {
   "title": "Avg Response Time (ms)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "data.event_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.response_time", "id": "1", "type": "avg" }
     ],
     "timeField": "data.event_timestamp"
    }
   ]
  },
  {
   "title": "Transaction per F5 Device",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(f5_totRequests{virtualServers!=\"\"}[$__range])) by (instance)"
    }
   ]
  },
  {
   "title": "Top Virtual Servers",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(f5_totRequests{virtualServers=~\"(/Scale_out).*\"}[$__range])) by (virtualServers)"
    }
   ]
  },
  {
   "title": "Transactions over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(f5_totRequests{virtualServers=~\"(/Scale_out).*\"}[1m])"
    }
   ]
  },
  {
   "title": "Top 10 Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.client_ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "data.event_timestamp"
    }
   ]
  },
  {
   "title": "Top Continents",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "geoip.continent_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "data.event_timestamp"
    }
   ]
  },
  {
   "title": "Top 10 User-Agents",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.user_agent.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "data.event_timestamp"
    }
   ]
  },
  {
   "title": "Response Time over Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "data.event_timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "data.response_time",
       "id": "1",
       "settings": {},
       "type": "avg"
      },
      { "field": "data.response_time", "id": "4", "type": "max" }
     ],
     "timeField": "data.event_timestamp"
    }
   ]
  },
  {
   "title": "Response Time per URL",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.http_path.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "7[avg]", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "data.response_time",
       "id": "7",
       "meta": {
        "avg": true,
        "count": true,
        "max": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false,
        "sum": false
       },
       "type": "extended_stats"
      }
     ],
     "timeField": "data.event_timestamp"
    }
   ]
  },
  {
   "title": "World View",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "geoip.location", "id": "2", "settings": { "precision": "3" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "data.event_timestamp"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "data.event_timestamp"
    }
   ]
  }
 ]
}